# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class TestTestconnect():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    class TestTestconnect():
        def setup_method(self, method):
            self.driver = webdriver.Chrome()
            self.vars = {}

        def teardown_method(self, method):
            self.driver.quit()

        def test_testconnect(self):
            self.driver.get("https://app.novafi.xyz/")
            self.driver.set_window_size(1512, 854)

            # wait for the first "Connect Wallet" button to be clickable and click it
            connect_button_1 = WebDriverWait(self.driver, 10).until(
                EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn")))
            connect_button_1.click()

            # wait for the second "Connect Wallet" button to be clickable and click it
            connect_button_2 = WebDriverWait(self.driver, 10).until(
                EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn:nth-child(5)")))
            connect_button_2.click()
